INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AX', 'ALA', 'ÅLAND ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AF', 'AFG', 'AFGHANISTAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AL', 'ALB', 'ALBANIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('DZ', 'DZA', 'ALGERIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AS', 'ASM', 'AMERICAN SAMOA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AD', 'AND', 'ANDORRA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AO', 'AGO', 'ANGOLA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AI', 'AIA', 'ANGUILLA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AQ', 'ATA', 'ANTARCTICA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AG', 'ATG', 'ANTIGUA AND BARBUDA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AR', 'ARG', 'ARGENTINA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AM', 'ARM', 'ARMENIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AW', 'ABW', 'ARUBA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AU', 'AUS', 'AUSTRALIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AT', 'AUT', 'AUSTRIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AZ', 'AZE', 'AZERBAIJAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BS', 'BHS', 'BAHAMAS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BH', 'BHR', 'BAHRAIN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BD', 'BGD', 'BANGLADESH');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BB', 'BRB', 'BARBADOS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BY', 'BLR', 'BELARUS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BE', 'BEL', 'BELGIUM');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BZ', 'BLZ', 'BELIZE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BJ', 'BEN', 'BENIN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BM', 'BMU', 'BERMUDA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BT', 'BTN', 'BHUTAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BO', 'BOL', 'BOLIVIA, PLURINATIONAL STATE OF');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BQ', 'BES', 'BONAIRE, SINT EUSTATIUS AND SABA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BA', 'BIH', 'BOSNIA AND HERZEGOWINA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BW', 'BWA', 'BOTSWANA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BV', 'BVT', 'BOUVET ISLAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BR', 'BRA', 'BRAZIL');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IO', 'IOT', 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BN', 'BRN', 'BRUNEI DARUSSALAM');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BG', 'BGR', 'BULGARIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BF', 'BFA', 'BURKINA FASO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BI', 'BDI', 'BURUNDI');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KH', 'KHM', 'CAMBODIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CM', 'CMR', 'CAMEROON');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CA', 'CAN', 'CANADA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CV', 'CPV', 'CAPE VERDE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KY', 'CYM', 'CAYMAN ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CF', 'CAF', 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TD', 'TCD', 'CHAD');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CL', 'CHL', 'CHILE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CN', 'CHN', 'CHINA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CX', 'CXR', 'CHRISTMAS ISLAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CC', 'CCK', 'COCOS (KEELING) ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CO', 'COL', 'COLOMBIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KM', 'COM', 'COMOROS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CG', 'COG', 'CONGO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CD', 'COD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CK', 'COK', 'COOK ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CR', 'CRI', 'COSTA RICA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CI', 'CIV', 'COTE D IVOIRE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('HR', 'HRV', 'CROATIA (local name Hrvatska)');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CU', 'CUB', 'CUBA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CW', 'CUW', 'CURAÇAO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CY', 'CYP', 'CYPRUS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CZ', 'CZE', 'CZECH REPUBLIC');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('DK', 'DNK', 'DENMARK');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('DJ', 'DJI', 'DJIBOUTI');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('DM', 'DMA', 'DOMINICA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('DO', 'DOM', 'DOMINICAN REPUBLIC');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('EC', 'ECU', 'ECUADOR');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('EG', 'EGY', 'EGYPT');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SV', 'SLV', 'EL SALVADOR');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GQ', 'GNQ', 'EQUATORIAL GUINEA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ER', 'ERI', 'ERITREA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('EE', 'EST', 'ESTONIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ET', 'ETH', 'ETHIOPIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('FK', 'FLK', 'FALKLAND ISLANDS (MALVINAS)');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('FO', 'FRO', 'FAROE ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('FJ', 'FJI', 'FIJI');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('FI', 'FIN', 'FINLAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('FR', 'FRA', 'FRANCE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GF', 'GUF', 'FRENCH GUIANA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PF', 'PYF', 'FRENCH POLYNESIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TF', 'ATF', 'FRENCH SOUTHERN TERRITORIES');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GA', 'GAB', 'GABON');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GM', 'GMB', 'GAMBIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GE', 'GEO', 'GEORGIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('DE', 'DEU', 'GERMANY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GH', 'GHA', 'GHANA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GI', 'GIB', 'GIBRALTAR');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GR', 'GRC', 'GREECE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GL', 'GRL', 'GREENLAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GD', 'GRD', 'GRENADA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GP', 'GLP', 'GUADELOUPE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GU', 'GUM', 'GUAM');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GT', 'GTM', 'GUATEMALA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GG', 'GGY', 'GUERNSEY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GN', 'GIN', 'GUINEA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GW', 'GNB', 'GUINEA-BISSAU');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GY', 'GUY', 'GUYANA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('HT', 'HTI', 'HAITI');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('HM', 'HMD', 'HEARD AND MC DONALD ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('VA', 'VAT', 'HOLY SEE (VATICAN CITY STATE)');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('HN', 'HND', 'HONDURAS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('HK', 'HKG', 'HONG KONG');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('HU', 'HUN', 'HUNGARY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IS', 'ISL', 'ICELAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IN', 'IND', 'INDIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ID', 'IDN', 'INDONESIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IR', 'IRN', 'IRAN (ISLAMIC REPUBLIC OF)');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IQ', 'IRQ', 'IRAQ');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IE', 'IRL', 'IRELAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IM', 'IMN', 'ISLE OF MAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IL', 'ISR', 'ISRAEL');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('IT', 'ITA', 'ITALY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('JM', 'JAM', 'JAMAICA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('JP', 'JPN', 'JAPAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('JE', 'JEY', 'JERSEY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('JO', 'JOR', 'JORDAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KZ', 'KAZ', 'KAZAKHSTAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KE', 'KEN', 'KENYA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KI', 'KIR', 'KIRIBATI');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KP', 'PRK', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KR', 'KOR', 'KOREA, REPUBLIC OF');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KW', 'KWT', 'KUWAIT');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KG', 'KGZ', 'KYRGYZSTAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LA', 'LAO', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LV', 'LVA', 'LATVIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LB', 'LBN', 'LEBANON');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LS', 'LSO', 'LESOTHO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LR', 'LBR', 'LIBERIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LY', 'LBY', 'LIBYA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LI', 'LIE', 'LIECHTENSTEIN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LT', 'LTU', 'LITHUANIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LU', 'LUX', 'LUXEMBOURG');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MO', 'MAC', 'MACAO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MK', 'MKD', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MG', 'MDG', 'MADAGASCAR');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MW', 'MWI', 'MALAWI');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MY', 'MYS', 'MALAYSIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MV', 'MDV', 'MALDIVES');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ML', 'MLI', 'MALI');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MT', 'MLT', 'MALTA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MH', 'MHL', 'MARSHALL ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MQ', 'MTQ', 'MARTINIQUE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MR', 'MRT', 'MAURITANIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MU', 'MUS', 'MAURITIUS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('YT', 'MYT', 'MAYOTTE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MX', 'MEX', 'MEXICO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('FM', 'FSM', 'MICRONESIA, FEDERATED STATES OF');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MD', 'MDA', 'MOLDOVA, REPUBLIC OF');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MC', 'MCO', 'MONACO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MN', 'MNG', 'MONGOLIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ME', 'MNE', 'MONTENEGRO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MS', 'MSR', 'MONTSERRAT');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MA', 'MAR', 'MOROCCO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MZ', 'MOZ', 'MOZAMBIQUE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MM', 'MMR', 'MYANMAR');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NA', 'NAM', 'NAMIBIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NR', 'NRU', 'NAURU');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NP', 'NPL', 'NEPAL');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NL', 'NLD', 'NETHERLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NC', 'NCL', 'NEW CALEDONIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NZ', 'NZL', 'NEW ZEALAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NI', 'NIC', 'NICARAGUA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NE', 'NER', 'NIGER');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NG', 'NGA', 'NIGERIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NU', 'NIU', 'NIUE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NF', 'NFK', 'NORFOLK ISLAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('MP', 'MNP', 'NORTHERN MARIANA ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('NO', 'NOR', 'NORWAY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('OM', 'OMN', 'OMAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PK', 'PAK', 'PAKISTAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PW', 'PLW', 'PALAU');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PS', 'PSE', 'PALESTINIAN TERRITORY, OCCUPIED');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PA', 'PAN', 'PANAMA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PG', 'PNG', 'PAPUA NEW GUINEA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PY', 'PRY', 'PARAGUAY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PE', 'PER', 'PERU');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PH', 'PHL', 'PHILIPPINES');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PN', 'PCN', 'PITCAIRN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PL', 'POL', 'POLAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PT', 'PRT', 'PORTUGAL');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PR', 'PRI', 'PUERTO RICO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('QA', 'QAT', 'QATAR');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('RE', 'REU', 'REUNION');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('RO', 'ROU', 'ROMANIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('RU', 'RUS', 'RUSSIAN FEDERATION');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('RW', 'RWA', 'RWANDA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SH', 'SHN', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('BL', 'BLM', 'SAINT BARTHÉLEMY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('KN', 'KNA', 'SAINT KITTS AND NEVIS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LC', 'LCA', 'SAINT LUCIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('PM', 'SPM', 'SAINT PIERRE AND MIQUELON');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('VC', 'VCT', 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('WS', 'WSM', 'SAMOA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SM', 'SMR', 'SAN MARINO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ST', 'STP', 'SAO TOME AND PRINCIPE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SA', 'SAU', 'SAUDI ARABIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SN', 'SEN', 'SENEGAL');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('RS', 'SRB', 'SERBIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SC', 'SYC', 'SEYCHELLES');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SL', 'SLE', 'SIERRA LEONE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SG', 'SGP', 'SINGAPORE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SX', 'SXM', 'SINT MAARTEN (DUTCH PART)');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SK', 'SVK', 'SLOVAKIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SI', 'SVN', 'SLOVENIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SB', 'SLB', 'SOLOMON ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SO', 'SOM', 'SOMALIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ZA', 'ZAF', 'SOUTH AFRICA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GS', 'SGS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SS', 'SSD', 'SOUTH SUDAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ES', 'ESP', 'SPAIN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('LK', 'LKA', 'SRI LANKA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SD', 'SDN', 'SUDAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SR', 'SUR', 'SURINAME');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SJ', 'SJM', 'SVALBARD AND JAN MAYEN ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SZ', 'SWZ', 'SWAZILAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SE', 'SWE', 'SWEDEN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('CH', 'CHE', 'SWITZERLAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('SY', 'SYR', 'SYRIAN ARAB REPUBLIC');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TW', 'TWN', 'TAIWAN, PROVINCE OF CHINA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TJ', 'TJK', 'TAJIKISTAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TZ', 'TZA', 'TANZANIA, UNITED REPUBLIC OF');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TH', 'THA', 'THAILAND');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TL', 'TLS', 'TIMOR-LESTE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TG', 'TGO', 'TOGO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TK', 'TKL', 'TOKELAU');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TO', 'TON', 'TONGA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TT', 'TTO', 'TRINIDAD AND TOBAGO');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TN', 'TUN', 'TUNISIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TR', 'TUR', 'TURKEY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TM', 'TKM', 'TURKMENISTAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TC', 'TCA', 'TURKS AND CAICOS ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('TV', 'TUV', 'TUVALU');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('UG', 'UGA', 'UGANDA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('UA', 'UKR', 'UKRAINE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('AE', 'ARE', 'UNITED ARAB EMIRATES');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('GB', 'GBR', 'UNITED KINGDOM*');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('UK', 'GBR', 'UNITED KINGDOM*');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('US', 'USA', 'UNITED STATES');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('UM', 'UMI', 'UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('UY', 'URY', 'URUGUAY');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('UZ', 'UZB', 'UZBEKISTAN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('VU', 'VUT', 'VANUATU');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('VE', 'VEN', 'VENEZUELA, BOLIVARIAN REPUBLIC OF');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('VN', 'VNM', 'VIET NAM');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('VG', 'VGB', 'VIRGIN ISLANDS (BRITISH)');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('VI', 'VIR', 'VIRGIN ISLANDS (U.S.)');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('WF', 'WLF', 'WALLIS AND FUTUNA ISLANDS');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('EH', 'ESH', 'WESTERN SAHARA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('YE', 'YEM', 'YEMEN');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ZM', 'ZMB', 'ZAMBIA');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('ZW', 'ZWE', 'ZIMBABWE');
INSERT INTO contactdb_countrycode (cc, cc3, country_name) VALUES ('EU', 'EUR', 'Europe');
